### ISSUE TITLE
Weird horizontal bands of nan in resultant fits files

### ISSUE THREAD

**Issue by ajwheeler** [esheldon/galsim_extra#5]
I'm working on a config module that applies noise specified by the weightmap in a real FITS file.  I've been testing this with a modified version of `focal.yaml`, but for some weightmaps the output has horizontal bands of `nan` "over" the image.
![weird_bands](https://cloud.githubusercontent.com/assets/711963/26744144/bcf15b7c-47b2-11e7-8109-b2b1410a8c8f.png)

Have you seen this before?  Applying uniform noise to the image does not have the same effect, and I have verified that the images don't have these bands as the leave my `addNoise` function by outputting at the end of it with
```
galsim.fits.write(im, "test.fits.fz")
```
.

**Comment by NiallMac** [comment]
Adam - could you post your modified yaml file, and the code in your new module that does this noise application? @rmjarvis have you seen anything like this before?

**Comment by ajwheeler** [comment]
[Here's my noise module](https://github.com/ajwheeler/galsim_extra/blob/master/galsim_extra/fits_noise.py) (also copied below).
```import galsim                                                                                          
from astropy.io import fits
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import numpy as np

class FitsNoiseBuilder(galsim.config.NoiseBuilder):
    def addNoise(self, config, base, im, rng, current_var, draw_method, logger):
        """
        @param config           The configuration dict for the noise field.
        @param base             The base configuration dict.
        @param im               The image onto which to add the noise
        @param rng              The random number generator to use for adding the noise.
        @param current_var      The current noise variance present in the image already [default: 0]
        @param logger           If given, a logger object to log progress.
        """
        var = self.getNoiseVariance(config, base)
        noise = galsim.noise.VariableGaussianNoise(rng, var)
        im.addNoise(noise)
        galsim.fits.write(im, "test.fits.fz")

    def getNoiseVariance(self, config, base):
        req = {'hdu': int, 'file_name': str}
        opt = {'dir': str}
        params, safe = galsim.config.GetAllParams(config, base, req=req, opt=opt)

        filename = params.get('dir', '.') + '/' + params['file_name']

        hdus = fits.open(filename)
        hdu = hdus[params['hdu']]
        hdu.verify('silentfix')

        varmap = 1.0/hdu.data

        return galsim.image.Image(varmap)

galsim.config.RegisterNoiseType('FitsNoise', FitsNoiseBuilder())                                       
```

[Here's my version of focal.yaml](https://github.com/ajwheeler/galsim_extra/blob/master/examples/focal.yaml) .  The differences are 
1. that the RandomWalk section of the galaxy defs has been commented out
2. the sky level is set to a specific value, not chosen randomly
3. the expected no. of objects is set to `mean: "$(8000*@output.nchips)"`
4. `nchips: 1`
5. 
```
noise:
        type: FitsNoise
        hdu: 3
        dir: '@image.wcs.dir'
        file_name: '@image.wcs.file_name'
```

**Comment by rmjarvis** [comment]
I don't get anything like that running on the exp_list that is in the repo.  

<img width="760" alt="aj" src="https://cloud.githubusercontent.com/assets/623887/26797187/0966d29a-49fa-11e7-84a1-fac31f118b98.png">

But this isn't for the same DES image as you are apparently using (different id number).  So could you package up a complete tarball that reproduces the problem you're seeing including the relevant input files?  Otherwise it is hard to diagnose the problem.

OTOH, my off-the-cuff guess as to where the problem might be is in the astropy rice compression.  You could try not outputting to a .fz file.  Also, if you astropy version is old, you might try updating that.  (Although even odds at best on whether that will fix the bug or introduce new bugs.  Their quality control isn't great in my experience.)

And btw, I like the FitsNoiseBuilder you wrote.  That's very nice.

**Comment by ajwheeler** [comment]
It was the compression!  Thanks so much!
Unfortunately, upgrading from astropy 1.3.2 to 1.3.3 didn't fix it, but it's trivial to work around.
